// encrypt.v

// Generated using ACDS version 23.1 993

`timescale 1 ps / 1 ps
module encrypt (
		input  wire [3:0]  button_export,      //      button.export
		input  wire        clk_clk,            //         clk.clk
		output wire [6:0]  displayhex0_export, // displayhex0.export
		output wire [6:0]  displayhex1_export, // displayhex1.export
		output wire [6:0]  displayhex2_export, // displayhex2.export
		output wire [6:0]  displayhex3_export, // displayhex3.export
		output wire [6:0]  displayhex4_export, // displayhex4.export
		output wire [6:0]  displayhex5_export, // displayhex5.export
		output wire [9:0]  leds_export,        //        leds.export
		output wire        sdram_clk_clk,      //   sdram_clk.clk
		output wire [12:0] sdram_wire_addr,    //  sdram_wire.addr
		output wire [1:0]  sdram_wire_ba,      //            .ba
		output wire        sdram_wire_cas_n,   //            .cas_n
		output wire        sdram_wire_cke,     //            .cke
		output wire        sdram_wire_cs_n,    //            .cs_n
		inout  wire [15:0] sdram_wire_dq,      //            .dq
		output wire [1:0]  sdram_wire_dqm,     //            .dqm
		output wire        sdram_wire_ras_n,   //            .ras_n
		output wire        sdram_wire_we_n,    //            .we_n
		input  wire [9:0]  switch_export       //      switch.export
	);

	wire         clock_sys_clk_clk;                                      // CLOCK:sys_clk_clk -> [BUTTONS:clk, CustomIP_0:clk, DEBUG:clk, HEX0:clk, HEX1:clk, HEX2:clk, HEX3:clk, HEX4:clk, HEX5:clk, LEDS:clk, NIOSV:clk, SDRAM:clk, SWITCHES:clk, irq_mapper:clk, mm_interconnect_0:CLOCK_sys_clk_clk, rst_controller:clk]
	wire         niosv_dbg_reset_out_reset;                              // NIOSV:dbg_reset_out_reset -> [CLOCK:ref_reset_reset, NIOSV:ndm_reset_in_reset, rst_controller:reset_in0]
	wire  [31:0] niosv_data_manager_awaddr;                              // NIOSV:data_manager_awaddr -> mm_interconnect_0:NIOSV_data_manager_awaddr
	wire   [1:0] niosv_data_manager_bresp;                               // mm_interconnect_0:NIOSV_data_manager_bresp -> NIOSV:data_manager_bresp
	wire         niosv_data_manager_arready;                             // mm_interconnect_0:NIOSV_data_manager_arready -> NIOSV:data_manager_arready
	wire  [31:0] niosv_data_manager_rdata;                               // mm_interconnect_0:NIOSV_data_manager_rdata -> NIOSV:data_manager_rdata
	wire   [3:0] niosv_data_manager_wstrb;                               // NIOSV:data_manager_wstrb -> mm_interconnect_0:NIOSV_data_manager_wstrb
	wire         niosv_data_manager_wready;                              // mm_interconnect_0:NIOSV_data_manager_wready -> NIOSV:data_manager_wready
	wire         niosv_data_manager_awready;                             // mm_interconnect_0:NIOSV_data_manager_awready -> NIOSV:data_manager_awready
	wire         niosv_data_manager_rready;                              // NIOSV:data_manager_rready -> mm_interconnect_0:NIOSV_data_manager_rready
	wire         niosv_data_manager_bready;                              // NIOSV:data_manager_bready -> mm_interconnect_0:NIOSV_data_manager_bready
	wire         niosv_data_manager_wvalid;                              // NIOSV:data_manager_wvalid -> mm_interconnect_0:NIOSV_data_manager_wvalid
	wire  [31:0] niosv_data_manager_araddr;                              // NIOSV:data_manager_araddr -> mm_interconnect_0:NIOSV_data_manager_araddr
	wire   [2:0] niosv_data_manager_arprot;                              // NIOSV:data_manager_arprot -> mm_interconnect_0:NIOSV_data_manager_arprot
	wire   [1:0] niosv_data_manager_rresp;                               // mm_interconnect_0:NIOSV_data_manager_rresp -> NIOSV:data_manager_rresp
	wire   [2:0] niosv_data_manager_awprot;                              // NIOSV:data_manager_awprot -> mm_interconnect_0:NIOSV_data_manager_awprot
	wire  [31:0] niosv_data_manager_wdata;                               // NIOSV:data_manager_wdata -> mm_interconnect_0:NIOSV_data_manager_wdata
	wire         niosv_data_manager_arvalid;                             // NIOSV:data_manager_arvalid -> mm_interconnect_0:NIOSV_data_manager_arvalid
	wire         niosv_data_manager_bvalid;                              // mm_interconnect_0:NIOSV_data_manager_bvalid -> NIOSV:data_manager_bvalid
	wire         niosv_data_manager_awvalid;                             // NIOSV:data_manager_awvalid -> mm_interconnect_0:NIOSV_data_manager_awvalid
	wire         niosv_data_manager_rvalid;                              // mm_interconnect_0:NIOSV_data_manager_rvalid -> NIOSV:data_manager_rvalid
	wire  [31:0] niosv_instruction_manager_awaddr;                       // NIOSV:instruction_manager_awaddr -> mm_interconnect_0:NIOSV_instruction_manager_awaddr
	wire   [1:0] niosv_instruction_manager_bresp;                        // mm_interconnect_0:NIOSV_instruction_manager_bresp -> NIOSV:instruction_manager_bresp
	wire         niosv_instruction_manager_arready;                      // mm_interconnect_0:NIOSV_instruction_manager_arready -> NIOSV:instruction_manager_arready
	wire  [31:0] niosv_instruction_manager_rdata;                        // mm_interconnect_0:NIOSV_instruction_manager_rdata -> NIOSV:instruction_manager_rdata
	wire   [3:0] niosv_instruction_manager_wstrb;                        // NIOSV:instruction_manager_wstrb -> mm_interconnect_0:NIOSV_instruction_manager_wstrb
	wire         niosv_instruction_manager_wready;                       // mm_interconnect_0:NIOSV_instruction_manager_wready -> NIOSV:instruction_manager_wready
	wire         niosv_instruction_manager_awready;                      // mm_interconnect_0:NIOSV_instruction_manager_awready -> NIOSV:instruction_manager_awready
	wire         niosv_instruction_manager_rready;                       // NIOSV:instruction_manager_rready -> mm_interconnect_0:NIOSV_instruction_manager_rready
	wire         niosv_instruction_manager_bready;                       // NIOSV:instruction_manager_bready -> mm_interconnect_0:NIOSV_instruction_manager_bready
	wire         niosv_instruction_manager_wvalid;                       // NIOSV:instruction_manager_wvalid -> mm_interconnect_0:NIOSV_instruction_manager_wvalid
	wire  [31:0] niosv_instruction_manager_araddr;                       // NIOSV:instruction_manager_araddr -> mm_interconnect_0:NIOSV_instruction_manager_araddr
	wire   [2:0] niosv_instruction_manager_arprot;                       // NIOSV:instruction_manager_arprot -> mm_interconnect_0:NIOSV_instruction_manager_arprot
	wire   [1:0] niosv_instruction_manager_rresp;                        // mm_interconnect_0:NIOSV_instruction_manager_rresp -> NIOSV:instruction_manager_rresp
	wire   [2:0] niosv_instruction_manager_awprot;                       // NIOSV:instruction_manager_awprot -> mm_interconnect_0:NIOSV_instruction_manager_awprot
	wire  [31:0] niosv_instruction_manager_wdata;                        // NIOSV:instruction_manager_wdata -> mm_interconnect_0:NIOSV_instruction_manager_wdata
	wire         niosv_instruction_manager_arvalid;                      // NIOSV:instruction_manager_arvalid -> mm_interconnect_0:NIOSV_instruction_manager_arvalid
	wire         niosv_instruction_manager_bvalid;                       // mm_interconnect_0:NIOSV_instruction_manager_bvalid -> NIOSV:instruction_manager_bvalid
	wire         niosv_instruction_manager_awvalid;                      // NIOSV:instruction_manager_awvalid -> mm_interconnect_0:NIOSV_instruction_manager_awvalid
	wire         niosv_instruction_manager_rvalid;                       // mm_interconnect_0:NIOSV_instruction_manager_rvalid -> NIOSV:instruction_manager_rvalid
	wire         mm_interconnect_0_debug_avalon_jtag_slave_chipselect;   // mm_interconnect_0:DEBUG_avalon_jtag_slave_chipselect -> DEBUG:av_chipselect
	wire  [31:0] mm_interconnect_0_debug_avalon_jtag_slave_readdata;     // DEBUG:av_readdata -> mm_interconnect_0:DEBUG_avalon_jtag_slave_readdata
	wire         mm_interconnect_0_debug_avalon_jtag_slave_waitrequest;  // DEBUG:av_waitrequest -> mm_interconnect_0:DEBUG_avalon_jtag_slave_waitrequest
	wire   [0:0] mm_interconnect_0_debug_avalon_jtag_slave_address;      // mm_interconnect_0:DEBUG_avalon_jtag_slave_address -> DEBUG:av_address
	wire         mm_interconnect_0_debug_avalon_jtag_slave_read;         // mm_interconnect_0:DEBUG_avalon_jtag_slave_read -> DEBUG:av_read_n
	wire         mm_interconnect_0_debug_avalon_jtag_slave_write;        // mm_interconnect_0:DEBUG_avalon_jtag_slave_write -> DEBUG:av_write_n
	wire  [31:0] mm_interconnect_0_debug_avalon_jtag_slave_writedata;    // mm_interconnect_0:DEBUG_avalon_jtag_slave_writedata -> DEBUG:av_writedata
	wire         mm_interconnect_0_customip_0_avalon_slave_0_chipselect; // mm_interconnect_0:CustomIP_0_avalon_slave_0_chipselect -> CustomIP_0:chipselect
	wire  [31:0] mm_interconnect_0_customip_0_avalon_slave_0_readdata;   // CustomIP_0:readdata -> mm_interconnect_0:CustomIP_0_avalon_slave_0_readdata
	wire   [1:0] mm_interconnect_0_customip_0_avalon_slave_0_address;    // mm_interconnect_0:CustomIP_0_avalon_slave_0_address -> CustomIP_0:address
	wire         mm_interconnect_0_customip_0_avalon_slave_0_read;       // mm_interconnect_0:CustomIP_0_avalon_slave_0_read -> CustomIP_0:read
	wire         mm_interconnect_0_customip_0_avalon_slave_0_write;      // mm_interconnect_0:CustomIP_0_avalon_slave_0_write -> CustomIP_0:write
	wire  [31:0] mm_interconnect_0_customip_0_avalon_slave_0_writedata;  // mm_interconnect_0:CustomIP_0_avalon_slave_0_writedata -> CustomIP_0:writedata
	wire  [31:0] mm_interconnect_0_niosv_dm_agent_readdata;              // NIOSV:dm_agent_readdata -> mm_interconnect_0:NIOSV_dm_agent_readdata
	wire         mm_interconnect_0_niosv_dm_agent_waitrequest;           // NIOSV:dm_agent_waitrequest -> mm_interconnect_0:NIOSV_dm_agent_waitrequest
	wire  [15:0] mm_interconnect_0_niosv_dm_agent_address;               // mm_interconnect_0:NIOSV_dm_agent_address -> NIOSV:dm_agent_address
	wire         mm_interconnect_0_niosv_dm_agent_read;                  // mm_interconnect_0:NIOSV_dm_agent_read -> NIOSV:dm_agent_read
	wire         mm_interconnect_0_niosv_dm_agent_readdatavalid;         // NIOSV:dm_agent_readdatavalid -> mm_interconnect_0:NIOSV_dm_agent_readdatavalid
	wire         mm_interconnect_0_niosv_dm_agent_write;                 // mm_interconnect_0:NIOSV_dm_agent_write -> NIOSV:dm_agent_write
	wire  [31:0] mm_interconnect_0_niosv_dm_agent_writedata;             // mm_interconnect_0:NIOSV_dm_agent_writedata -> NIOSV:dm_agent_writedata
	wire         mm_interconnect_0_sdram_s1_chipselect;                  // mm_interconnect_0:SDRAM_s1_chipselect -> SDRAM:az_cs
	wire  [15:0] mm_interconnect_0_sdram_s1_readdata;                    // SDRAM:za_data -> mm_interconnect_0:SDRAM_s1_readdata
	wire         mm_interconnect_0_sdram_s1_waitrequest;                 // SDRAM:za_waitrequest -> mm_interconnect_0:SDRAM_s1_waitrequest
	wire  [24:0] mm_interconnect_0_sdram_s1_address;                     // mm_interconnect_0:SDRAM_s1_address -> SDRAM:az_addr
	wire         mm_interconnect_0_sdram_s1_read;                        // mm_interconnect_0:SDRAM_s1_read -> SDRAM:az_rd_n
	wire   [1:0] mm_interconnect_0_sdram_s1_byteenable;                  // mm_interconnect_0:SDRAM_s1_byteenable -> SDRAM:az_be_n
	wire         mm_interconnect_0_sdram_s1_readdatavalid;               // SDRAM:za_valid -> mm_interconnect_0:SDRAM_s1_readdatavalid
	wire         mm_interconnect_0_sdram_s1_write;                       // mm_interconnect_0:SDRAM_s1_write -> SDRAM:az_wr_n
	wire  [15:0] mm_interconnect_0_sdram_s1_writedata;                   // mm_interconnect_0:SDRAM_s1_writedata -> SDRAM:az_data
	wire  [31:0] mm_interconnect_0_switches_s1_readdata;                 // SWITCHES:readdata -> mm_interconnect_0:SWITCHES_s1_readdata
	wire   [1:0] mm_interconnect_0_switches_s1_address;                  // mm_interconnect_0:SWITCHES_s1_address -> SWITCHES:address
	wire         mm_interconnect_0_leds_s1_chipselect;                   // mm_interconnect_0:LEDS_s1_chipselect -> LEDS:chipselect
	wire  [31:0] mm_interconnect_0_leds_s1_readdata;                     // LEDS:readdata -> mm_interconnect_0:LEDS_s1_readdata
	wire   [1:0] mm_interconnect_0_leds_s1_address;                      // mm_interconnect_0:LEDS_s1_address -> LEDS:address
	wire         mm_interconnect_0_leds_s1_write;                        // mm_interconnect_0:LEDS_s1_write -> LEDS:write_n
	wire  [31:0] mm_interconnect_0_leds_s1_writedata;                    // mm_interconnect_0:LEDS_s1_writedata -> LEDS:writedata
	wire  [31:0] mm_interconnect_0_buttons_s1_readdata;                  // BUTTONS:readdata -> mm_interconnect_0:BUTTONS_s1_readdata
	wire   [1:0] mm_interconnect_0_buttons_s1_address;                   // mm_interconnect_0:BUTTONS_s1_address -> BUTTONS:address
	wire         mm_interconnect_0_hex0_s1_chipselect;                   // mm_interconnect_0:HEX0_s1_chipselect -> HEX0:chipselect
	wire  [31:0] mm_interconnect_0_hex0_s1_readdata;                     // HEX0:readdata -> mm_interconnect_0:HEX0_s1_readdata
	wire   [1:0] mm_interconnect_0_hex0_s1_address;                      // mm_interconnect_0:HEX0_s1_address -> HEX0:address
	wire         mm_interconnect_0_hex0_s1_write;                        // mm_interconnect_0:HEX0_s1_write -> HEX0:write_n
	wire  [31:0] mm_interconnect_0_hex0_s1_writedata;                    // mm_interconnect_0:HEX0_s1_writedata -> HEX0:writedata
	wire         mm_interconnect_0_hex1_s1_chipselect;                   // mm_interconnect_0:HEX1_s1_chipselect -> HEX1:chipselect
	wire  [31:0] mm_interconnect_0_hex1_s1_readdata;                     // HEX1:readdata -> mm_interconnect_0:HEX1_s1_readdata
	wire   [1:0] mm_interconnect_0_hex1_s1_address;                      // mm_interconnect_0:HEX1_s1_address -> HEX1:address
	wire         mm_interconnect_0_hex1_s1_write;                        // mm_interconnect_0:HEX1_s1_write -> HEX1:write_n
	wire  [31:0] mm_interconnect_0_hex1_s1_writedata;                    // mm_interconnect_0:HEX1_s1_writedata -> HEX1:writedata
	wire         mm_interconnect_0_hex2_s1_chipselect;                   // mm_interconnect_0:HEX2_s1_chipselect -> HEX2:chipselect
	wire  [31:0] mm_interconnect_0_hex2_s1_readdata;                     // HEX2:readdata -> mm_interconnect_0:HEX2_s1_readdata
	wire   [1:0] mm_interconnect_0_hex2_s1_address;                      // mm_interconnect_0:HEX2_s1_address -> HEX2:address
	wire         mm_interconnect_0_hex2_s1_write;                        // mm_interconnect_0:HEX2_s1_write -> HEX2:write_n
	wire  [31:0] mm_interconnect_0_hex2_s1_writedata;                    // mm_interconnect_0:HEX2_s1_writedata -> HEX2:writedata
	wire         mm_interconnect_0_hex3_s1_chipselect;                   // mm_interconnect_0:HEX3_s1_chipselect -> HEX3:chipselect
	wire  [31:0] mm_interconnect_0_hex3_s1_readdata;                     // HEX3:readdata -> mm_interconnect_0:HEX3_s1_readdata
	wire   [1:0] mm_interconnect_0_hex3_s1_address;                      // mm_interconnect_0:HEX3_s1_address -> HEX3:address
	wire         mm_interconnect_0_hex3_s1_write;                        // mm_interconnect_0:HEX3_s1_write -> HEX3:write_n
	wire  [31:0] mm_interconnect_0_hex3_s1_writedata;                    // mm_interconnect_0:HEX3_s1_writedata -> HEX3:writedata
	wire         mm_interconnect_0_hex4_s1_chipselect;                   // mm_interconnect_0:HEX4_s1_chipselect -> HEX4:chipselect
	wire  [31:0] mm_interconnect_0_hex4_s1_readdata;                     // HEX4:readdata -> mm_interconnect_0:HEX4_s1_readdata
	wire   [1:0] mm_interconnect_0_hex4_s1_address;                      // mm_interconnect_0:HEX4_s1_address -> HEX4:address
	wire         mm_interconnect_0_hex4_s1_write;                        // mm_interconnect_0:HEX4_s1_write -> HEX4:write_n
	wire  [31:0] mm_interconnect_0_hex4_s1_writedata;                    // mm_interconnect_0:HEX4_s1_writedata -> HEX4:writedata
	wire         mm_interconnect_0_hex5_s1_chipselect;                   // mm_interconnect_0:HEX5_s1_chipselect -> HEX5:chipselect
	wire  [31:0] mm_interconnect_0_hex5_s1_readdata;                     // HEX5:readdata -> mm_interconnect_0:HEX5_s1_readdata
	wire   [1:0] mm_interconnect_0_hex5_s1_address;                      // mm_interconnect_0:HEX5_s1_address -> HEX5:address
	wire         mm_interconnect_0_hex5_s1_write;                        // mm_interconnect_0:HEX5_s1_write -> HEX5:write_n
	wire  [31:0] mm_interconnect_0_hex5_s1_writedata;                    // mm_interconnect_0:HEX5_s1_writedata -> HEX5:writedata
	wire  [31:0] mm_interconnect_0_niosv_timer_sw_agent_readdata;        // NIOSV:timer_sw_agent_readdata -> mm_interconnect_0:NIOSV_timer_sw_agent_readdata
	wire         mm_interconnect_0_niosv_timer_sw_agent_waitrequest;     // NIOSV:timer_sw_agent_waitrequest -> mm_interconnect_0:NIOSV_timer_sw_agent_waitrequest
	wire   [5:0] mm_interconnect_0_niosv_timer_sw_agent_address;         // mm_interconnect_0:NIOSV_timer_sw_agent_address -> NIOSV:timer_sw_agent_address
	wire         mm_interconnect_0_niosv_timer_sw_agent_read;            // mm_interconnect_0:NIOSV_timer_sw_agent_read -> NIOSV:timer_sw_agent_read
	wire   [3:0] mm_interconnect_0_niosv_timer_sw_agent_byteenable;      // mm_interconnect_0:NIOSV_timer_sw_agent_byteenable -> NIOSV:timer_sw_agent_byteenable
	wire         mm_interconnect_0_niosv_timer_sw_agent_readdatavalid;   // NIOSV:timer_sw_agent_readdatavalid -> mm_interconnect_0:NIOSV_timer_sw_agent_readdatavalid
	wire         mm_interconnect_0_niosv_timer_sw_agent_write;           // mm_interconnect_0:NIOSV_timer_sw_agent_write -> NIOSV:timer_sw_agent_write
	wire  [31:0] mm_interconnect_0_niosv_timer_sw_agent_writedata;       // mm_interconnect_0:NIOSV_timer_sw_agent_writedata -> NIOSV:timer_sw_agent_writedata
	wire         irq_mapper_receiver0_irq;                               // DEBUG:av_irq -> irq_mapper:receiver0_irq
	wire  [15:0] niosv_platform_irq_rx_irq;                              // irq_mapper:sender_irq -> NIOSV:platform_irq_rx_irq
	wire         rst_controller_reset_out_reset;                         // rst_controller:reset_out -> [BUTTONS:reset_n, CustomIP_0:reset_n, DEBUG:rst_n, HEX0:reset_n, HEX1:reset_n, HEX2:reset_n, HEX3:reset_n, HEX4:reset_n, HEX5:reset_n, LEDS:reset_n, NIOSV:reset_reset, SDRAM:reset_n, SWITCHES:reset_n, irq_mapper:reset, mm_interconnect_0:NIOSV_reset_reset_bridge_in_reset_reset]

	encrypt_BUTTONS buttons (
		.clk      (clock_sys_clk_clk),                     //                 clk.clk
		.reset_n  (~rst_controller_reset_out_reset),       //               reset.reset_n
		.address  (mm_interconnect_0_buttons_s1_address),  //                  s1.address
		.readdata (mm_interconnect_0_buttons_s1_readdata), //                    .readdata
		.in_port  (button_export)                          // external_connection.export
	);

	encrypt_CLOCK clock (
		.ref_clk_clk        (clk_clk),                   //      ref_clk.clk
		.ref_reset_reset    (niosv_dbg_reset_out_reset), //    ref_reset.reset
		.sys_clk_clk        (clock_sys_clk_clk),         //      sys_clk.clk
		.sdram_clk_clk      (sdram_clk_clk),             //    sdram_clk.clk
		.reset_source_reset ()                           // reset_source.reset
	);

	encryptIP customip_0 (
		.address    (mm_interconnect_0_customip_0_avalon_slave_0_address),    // avalon_slave_0.address
		.chipselect (mm_interconnect_0_customip_0_avalon_slave_0_chipselect), //               .chipselect
		.read       (mm_interconnect_0_customip_0_avalon_slave_0_read),       //               .read
		.write      (mm_interconnect_0_customip_0_avalon_slave_0_write),      //               .write
		.writedata  (mm_interconnect_0_customip_0_avalon_slave_0_writedata),  //               .writedata
		.readdata   (mm_interconnect_0_customip_0_avalon_slave_0_readdata),   //               .readdata
		.clk        (clock_sys_clk_clk),                                      //          clock.clk
		.reset_n    (~rst_controller_reset_out_reset)                         //          reset.reset_n
	);

	encrypt_DEBUG debug (
		.clk            (clock_sys_clk_clk),                                     //               clk.clk
		.rst_n          (~rst_controller_reset_out_reset),                       //             reset.reset_n
		.av_chipselect  (mm_interconnect_0_debug_avalon_jtag_slave_chipselect),  // avalon_jtag_slave.chipselect
		.av_address     (mm_interconnect_0_debug_avalon_jtag_slave_address),     //                  .address
		.av_read_n      (~mm_interconnect_0_debug_avalon_jtag_slave_read),       //                  .read_n
		.av_readdata    (mm_interconnect_0_debug_avalon_jtag_slave_readdata),    //                  .readdata
		.av_write_n     (~mm_interconnect_0_debug_avalon_jtag_slave_write),      //                  .write_n
		.av_writedata   (mm_interconnect_0_debug_avalon_jtag_slave_writedata),   //                  .writedata
		.av_waitrequest (mm_interconnect_0_debug_avalon_jtag_slave_waitrequest), //                  .waitrequest
		.av_irq         (irq_mapper_receiver0_irq)                               //               irq.irq
	);

	encrypt_HEX0 hex0 (
		.clk        (clock_sys_clk_clk),                    //                 clk.clk
		.reset_n    (~rst_controller_reset_out_reset),      //               reset.reset_n
		.address    (mm_interconnect_0_hex0_s1_address),    //                  s1.address
		.write_n    (~mm_interconnect_0_hex0_s1_write),     //                    .write_n
		.writedata  (mm_interconnect_0_hex0_s1_writedata),  //                    .writedata
		.chipselect (mm_interconnect_0_hex0_s1_chipselect), //                    .chipselect
		.readdata   (mm_interconnect_0_hex0_s1_readdata),   //                    .readdata
		.out_port   (displayhex0_export)                    // external_connection.export
	);

	encrypt_HEX0 hex1 (
		.clk        (clock_sys_clk_clk),                    //                 clk.clk
		.reset_n    (~rst_controller_reset_out_reset),      //               reset.reset_n
		.address    (mm_interconnect_0_hex1_s1_address),    //                  s1.address
		.write_n    (~mm_interconnect_0_hex1_s1_write),     //                    .write_n
		.writedata  (mm_interconnect_0_hex1_s1_writedata),  //                    .writedata
		.chipselect (mm_interconnect_0_hex1_s1_chipselect), //                    .chipselect
		.readdata   (mm_interconnect_0_hex1_s1_readdata),   //                    .readdata
		.out_port   (displayhex1_export)                    // external_connection.export
	);

	encrypt_HEX0 hex2 (
		.clk        (clock_sys_clk_clk),                    //                 clk.clk
		.reset_n    (~rst_controller_reset_out_reset),      //               reset.reset_n
		.address    (mm_interconnect_0_hex2_s1_address),    //                  s1.address
		.write_n    (~mm_interconnect_0_hex2_s1_write),     //                    .write_n
		.writedata  (mm_interconnect_0_hex2_s1_writedata),  //                    .writedata
		.chipselect (mm_interconnect_0_hex2_s1_chipselect), //                    .chipselect
		.readdata   (mm_interconnect_0_hex2_s1_readdata),   //                    .readdata
		.out_port   (displayhex2_export)                    // external_connection.export
	);

	encrypt_HEX0 hex3 (
		.clk        (clock_sys_clk_clk),                    //                 clk.clk
		.reset_n    (~rst_controller_reset_out_reset),      //               reset.reset_n
		.address    (mm_interconnect_0_hex3_s1_address),    //                  s1.address
		.write_n    (~mm_interconnect_0_hex3_s1_write),     //                    .write_n
		.writedata  (mm_interconnect_0_hex3_s1_writedata),  //                    .writedata
		.chipselect (mm_interconnect_0_hex3_s1_chipselect), //                    .chipselect
		.readdata   (mm_interconnect_0_hex3_s1_readdata),   //                    .readdata
		.out_port   (displayhex3_export)                    // external_connection.export
	);

	encrypt_HEX0 hex4 (
		.clk        (clock_sys_clk_clk),                    //                 clk.clk
		.reset_n    (~rst_controller_reset_out_reset),      //               reset.reset_n
		.address    (mm_interconnect_0_hex4_s1_address),    //                  s1.address
		.write_n    (~mm_interconnect_0_hex4_s1_write),     //                    .write_n
		.writedata  (mm_interconnect_0_hex4_s1_writedata),  //                    .writedata
		.chipselect (mm_interconnect_0_hex4_s1_chipselect), //                    .chipselect
		.readdata   (mm_interconnect_0_hex4_s1_readdata),   //                    .readdata
		.out_port   (displayhex4_export)                    // external_connection.export
	);

	encrypt_HEX0 hex5 (
		.clk        (clock_sys_clk_clk),                    //                 clk.clk
		.reset_n    (~rst_controller_reset_out_reset),      //               reset.reset_n
		.address    (mm_interconnect_0_hex5_s1_address),    //                  s1.address
		.write_n    (~mm_interconnect_0_hex5_s1_write),     //                    .write_n
		.writedata  (mm_interconnect_0_hex5_s1_writedata),  //                    .writedata
		.chipselect (mm_interconnect_0_hex5_s1_chipselect), //                    .chipselect
		.readdata   (mm_interconnect_0_hex5_s1_readdata),   //                    .readdata
		.out_port   (displayhex5_export)                    // external_connection.export
	);

	encrypt_LEDS leds (
		.clk        (clock_sys_clk_clk),                    //                 clk.clk
		.reset_n    (~rst_controller_reset_out_reset),      //               reset.reset_n
		.address    (mm_interconnect_0_leds_s1_address),    //                  s1.address
		.write_n    (~mm_interconnect_0_leds_s1_write),     //                    .write_n
		.writedata  (mm_interconnect_0_leds_s1_writedata),  //                    .writedata
		.chipselect (mm_interconnect_0_leds_s1_chipselect), //                    .chipselect
		.readdata   (mm_interconnect_0_leds_s1_readdata),   //                    .readdata
		.out_port   (leds_export)                           // external_connection.export
	);

	encrypt_NIOSV niosv (
		.clk                          (clock_sys_clk_clk),                                    //                 clk.clk
		.reset_reset                  (rst_controller_reset_out_reset),                       //               reset.reset
		.platform_irq_rx_irq          (niosv_platform_irq_rx_irq),                            //     platform_irq_rx.irq
		.ndm_reset_in_reset           (niosv_dbg_reset_out_reset),                            //        ndm_reset_in.reset
		.timer_sw_agent_write         (mm_interconnect_0_niosv_timer_sw_agent_write),         //      timer_sw_agent.write
		.timer_sw_agent_writedata     (mm_interconnect_0_niosv_timer_sw_agent_writedata),     //                    .writedata
		.timer_sw_agent_byteenable    (mm_interconnect_0_niosv_timer_sw_agent_byteenable),    //                    .byteenable
		.timer_sw_agent_address       (mm_interconnect_0_niosv_timer_sw_agent_address),       //                    .address
		.timer_sw_agent_read          (mm_interconnect_0_niosv_timer_sw_agent_read),          //                    .read
		.timer_sw_agent_readdata      (mm_interconnect_0_niosv_timer_sw_agent_readdata),      //                    .readdata
		.timer_sw_agent_readdatavalid (mm_interconnect_0_niosv_timer_sw_agent_readdatavalid), //                    .readdatavalid
		.timer_sw_agent_waitrequest   (mm_interconnect_0_niosv_timer_sw_agent_waitrequest),   //                    .waitrequest
		.instruction_manager_awaddr   (niosv_instruction_manager_awaddr),                     // instruction_manager.awaddr
		.instruction_manager_awprot   (niosv_instruction_manager_awprot),                     //                    .awprot
		.instruction_manager_awvalid  (niosv_instruction_manager_awvalid),                    //                    .awvalid
		.instruction_manager_awready  (niosv_instruction_manager_awready),                    //                    .awready
		.instruction_manager_wdata    (niosv_instruction_manager_wdata),                      //                    .wdata
		.instruction_manager_wstrb    (niosv_instruction_manager_wstrb),                      //                    .wstrb
		.instruction_manager_wvalid   (niosv_instruction_manager_wvalid),                     //                    .wvalid
		.instruction_manager_wready   (niosv_instruction_manager_wready),                     //                    .wready
		.instruction_manager_bresp    (niosv_instruction_manager_bresp),                      //                    .bresp
		.instruction_manager_bvalid   (niosv_instruction_manager_bvalid),                     //                    .bvalid
		.instruction_manager_bready   (niosv_instruction_manager_bready),                     //                    .bready
		.instruction_manager_araddr   (niosv_instruction_manager_araddr),                     //                    .araddr
		.instruction_manager_arprot   (niosv_instruction_manager_arprot),                     //                    .arprot
		.instruction_manager_arvalid  (niosv_instruction_manager_arvalid),                    //                    .arvalid
		.instruction_manager_arready  (niosv_instruction_manager_arready),                    //                    .arready
		.instruction_manager_rdata    (niosv_instruction_manager_rdata),                      //                    .rdata
		.instruction_manager_rresp    (niosv_instruction_manager_rresp),                      //                    .rresp
		.instruction_manager_rvalid   (niosv_instruction_manager_rvalid),                     //                    .rvalid
		.instruction_manager_rready   (niosv_instruction_manager_rready),                     //                    .rready
		.data_manager_awaddr          (niosv_data_manager_awaddr),                            //        data_manager.awaddr
		.data_manager_awprot          (niosv_data_manager_awprot),                            //                    .awprot
		.data_manager_awvalid         (niosv_data_manager_awvalid),                           //                    .awvalid
		.data_manager_awready         (niosv_data_manager_awready),                           //                    .awready
		.data_manager_wdata           (niosv_data_manager_wdata),                             //                    .wdata
		.data_manager_wstrb           (niosv_data_manager_wstrb),                             //                    .wstrb
		.data_manager_wvalid          (niosv_data_manager_wvalid),                            //                    .wvalid
		.data_manager_wready          (niosv_data_manager_wready),                            //                    .wready
		.data_manager_bresp           (niosv_data_manager_bresp),                             //                    .bresp
		.data_manager_bvalid          (niosv_data_manager_bvalid),                            //                    .bvalid
		.data_manager_bready          (niosv_data_manager_bready),                            //                    .bready
		.data_manager_araddr          (niosv_data_manager_araddr),                            //                    .araddr
		.data_manager_arprot          (niosv_data_manager_arprot),                            //                    .arprot
		.data_manager_arvalid         (niosv_data_manager_arvalid),                           //                    .arvalid
		.data_manager_arready         (niosv_data_manager_arready),                           //                    .arready
		.data_manager_rdata           (niosv_data_manager_rdata),                             //                    .rdata
		.data_manager_rresp           (niosv_data_manager_rresp),                             //                    .rresp
		.data_manager_rvalid          (niosv_data_manager_rvalid),                            //                    .rvalid
		.data_manager_rready          (niosv_data_manager_rready),                            //                    .rready
		.dm_agent_write               (mm_interconnect_0_niosv_dm_agent_write),               //            dm_agent.write
		.dm_agent_writedata           (mm_interconnect_0_niosv_dm_agent_writedata),           //                    .writedata
		.dm_agent_address             (mm_interconnect_0_niosv_dm_agent_address),             //                    .address
		.dm_agent_read                (mm_interconnect_0_niosv_dm_agent_read),                //                    .read
		.dm_agent_readdata            (mm_interconnect_0_niosv_dm_agent_readdata),            //                    .readdata
		.dm_agent_readdatavalid       (mm_interconnect_0_niosv_dm_agent_readdatavalid),       //                    .readdatavalid
		.dm_agent_waitrequest         (mm_interconnect_0_niosv_dm_agent_waitrequest),         //                    .waitrequest
		.dbg_reset_out_reset          (niosv_dbg_reset_out_reset)                             //       dbg_reset_out.reset
	);

	encrypt_SDRAM sdram (
		.clk            (clock_sys_clk_clk),                        //   clk.clk
		.reset_n        (~rst_controller_reset_out_reset),          // reset.reset_n
		.az_addr        (mm_interconnect_0_sdram_s1_address),       //    s1.address
		.az_be_n        (~mm_interconnect_0_sdram_s1_byteenable),   //      .byteenable_n
		.az_cs          (mm_interconnect_0_sdram_s1_chipselect),    //      .chipselect
		.az_data        (mm_interconnect_0_sdram_s1_writedata),     //      .writedata
		.az_rd_n        (~mm_interconnect_0_sdram_s1_read),         //      .read_n
		.az_wr_n        (~mm_interconnect_0_sdram_s1_write),        //      .write_n
		.za_data        (mm_interconnect_0_sdram_s1_readdata),      //      .readdata
		.za_valid       (mm_interconnect_0_sdram_s1_readdatavalid), //      .readdatavalid
		.za_waitrequest (mm_interconnect_0_sdram_s1_waitrequest),   //      .waitrequest
		.zs_addr        (sdram_wire_addr),                          //  wire.export
		.zs_ba          (sdram_wire_ba),                            //      .export
		.zs_cas_n       (sdram_wire_cas_n),                         //      .export
		.zs_cke         (sdram_wire_cke),                           //      .export
		.zs_cs_n        (sdram_wire_cs_n),                          //      .export
		.zs_dq          (sdram_wire_dq),                            //      .export
		.zs_dqm         (sdram_wire_dqm),                           //      .export
		.zs_ras_n       (sdram_wire_ras_n),                         //      .export
		.zs_we_n        (sdram_wire_we_n)                           //      .export
	);

	encrypt_SWITCHES switches (
		.clk      (clock_sys_clk_clk),                      //                 clk.clk
		.reset_n  (~rst_controller_reset_out_reset),        //               reset.reset_n
		.address  (mm_interconnect_0_switches_s1_address),  //                  s1.address
		.readdata (mm_interconnect_0_switches_s1_readdata), //                    .readdata
		.in_port  (switch_export)                           // external_connection.export
	);

	encrypt_mm_interconnect_0 mm_interconnect_0 (
		.NIOSV_data_manager_awaddr               (niosv_data_manager_awaddr),                              //                NIOSV_data_manager.awaddr
		.NIOSV_data_manager_awprot               (niosv_data_manager_awprot),                              //                                  .awprot
		.NIOSV_data_manager_awvalid              (niosv_data_manager_awvalid),                             //                                  .awvalid
		.NIOSV_data_manager_awready              (niosv_data_manager_awready),                             //                                  .awready
		.NIOSV_data_manager_wdata                (niosv_data_manager_wdata),                               //                                  .wdata
		.NIOSV_data_manager_wstrb                (niosv_data_manager_wstrb),                               //                                  .wstrb
		.NIOSV_data_manager_wvalid               (niosv_data_manager_wvalid),                              //                                  .wvalid
		.NIOSV_data_manager_wready               (niosv_data_manager_wready),                              //                                  .wready
		.NIOSV_data_manager_bresp                (niosv_data_manager_bresp),                               //                                  .bresp
		.NIOSV_data_manager_bvalid               (niosv_data_manager_bvalid),                              //                                  .bvalid
		.NIOSV_data_manager_bready               (niosv_data_manager_bready),                              //                                  .bready
		.NIOSV_data_manager_araddr               (niosv_data_manager_araddr),                              //                                  .araddr
		.NIOSV_data_manager_arprot               (niosv_data_manager_arprot),                              //                                  .arprot
		.NIOSV_data_manager_arvalid              (niosv_data_manager_arvalid),                             //                                  .arvalid
		.NIOSV_data_manager_arready              (niosv_data_manager_arready),                             //                                  .arready
		.NIOSV_data_manager_rdata                (niosv_data_manager_rdata),                               //                                  .rdata
		.NIOSV_data_manager_rresp                (niosv_data_manager_rresp),                               //                                  .rresp
		.NIOSV_data_manager_rvalid               (niosv_data_manager_rvalid),                              //                                  .rvalid
		.NIOSV_data_manager_rready               (niosv_data_manager_rready),                              //                                  .rready
		.NIOSV_instruction_manager_awaddr        (niosv_instruction_manager_awaddr),                       //         NIOSV_instruction_manager.awaddr
		.NIOSV_instruction_manager_awprot        (niosv_instruction_manager_awprot),                       //                                  .awprot
		.NIOSV_instruction_manager_awvalid       (niosv_instruction_manager_awvalid),                      //                                  .awvalid
		.NIOSV_instruction_manager_awready       (niosv_instruction_manager_awready),                      //                                  .awready
		.NIOSV_instruction_manager_wdata         (niosv_instruction_manager_wdata),                        //                                  .wdata
		.NIOSV_instruction_manager_wstrb         (niosv_instruction_manager_wstrb),                        //                                  .wstrb
		.NIOSV_instruction_manager_wvalid        (niosv_instruction_manager_wvalid),                       //                                  .wvalid
		.NIOSV_instruction_manager_wready        (niosv_instruction_manager_wready),                       //                                  .wready
		.NIOSV_instruction_manager_bresp         (niosv_instruction_manager_bresp),                        //                                  .bresp
		.NIOSV_instruction_manager_bvalid        (niosv_instruction_manager_bvalid),                       //                                  .bvalid
		.NIOSV_instruction_manager_bready        (niosv_instruction_manager_bready),                       //                                  .bready
		.NIOSV_instruction_manager_araddr        (niosv_instruction_manager_araddr),                       //                                  .araddr
		.NIOSV_instruction_manager_arprot        (niosv_instruction_manager_arprot),                       //                                  .arprot
		.NIOSV_instruction_manager_arvalid       (niosv_instruction_manager_arvalid),                      //                                  .arvalid
		.NIOSV_instruction_manager_arready       (niosv_instruction_manager_arready),                      //                                  .arready
		.NIOSV_instruction_manager_rdata         (niosv_instruction_manager_rdata),                        //                                  .rdata
		.NIOSV_instruction_manager_rresp         (niosv_instruction_manager_rresp),                        //                                  .rresp
		.NIOSV_instruction_manager_rvalid        (niosv_instruction_manager_rvalid),                       //                                  .rvalid
		.NIOSV_instruction_manager_rready        (niosv_instruction_manager_rready),                       //                                  .rready
		.CLOCK_sys_clk_clk                       (clock_sys_clk_clk),                                      //                     CLOCK_sys_clk.clk
		.NIOSV_reset_reset_bridge_in_reset_reset (rst_controller_reset_out_reset),                         // NIOSV_reset_reset_bridge_in_reset.reset
		.BUTTONS_s1_address                      (mm_interconnect_0_buttons_s1_address),                   //                        BUTTONS_s1.address
		.BUTTONS_s1_readdata                     (mm_interconnect_0_buttons_s1_readdata),                  //                                  .readdata
		.CustomIP_0_avalon_slave_0_address       (mm_interconnect_0_customip_0_avalon_slave_0_address),    //         CustomIP_0_avalon_slave_0.address
		.CustomIP_0_avalon_slave_0_write         (mm_interconnect_0_customip_0_avalon_slave_0_write),      //                                  .write
		.CustomIP_0_avalon_slave_0_read          (mm_interconnect_0_customip_0_avalon_slave_0_read),       //                                  .read
		.CustomIP_0_avalon_slave_0_readdata      (mm_interconnect_0_customip_0_avalon_slave_0_readdata),   //                                  .readdata
		.CustomIP_0_avalon_slave_0_writedata     (mm_interconnect_0_customip_0_avalon_slave_0_writedata),  //                                  .writedata
		.CustomIP_0_avalon_slave_0_chipselect    (mm_interconnect_0_customip_0_avalon_slave_0_chipselect), //                                  .chipselect
		.DEBUG_avalon_jtag_slave_address         (mm_interconnect_0_debug_avalon_jtag_slave_address),      //           DEBUG_avalon_jtag_slave.address
		.DEBUG_avalon_jtag_slave_write           (mm_interconnect_0_debug_avalon_jtag_slave_write),        //                                  .write
		.DEBUG_avalon_jtag_slave_read            (mm_interconnect_0_debug_avalon_jtag_slave_read),         //                                  .read
		.DEBUG_avalon_jtag_slave_readdata        (mm_interconnect_0_debug_avalon_jtag_slave_readdata),     //                                  .readdata
		.DEBUG_avalon_jtag_slave_writedata       (mm_interconnect_0_debug_avalon_jtag_slave_writedata),    //                                  .writedata
		.DEBUG_avalon_jtag_slave_waitrequest     (mm_interconnect_0_debug_avalon_jtag_slave_waitrequest),  //                                  .waitrequest
		.DEBUG_avalon_jtag_slave_chipselect      (mm_interconnect_0_debug_avalon_jtag_slave_chipselect),   //                                  .chipselect
		.HEX0_s1_address                         (mm_interconnect_0_hex0_s1_address),                      //                           HEX0_s1.address
		.HEX0_s1_write                           (mm_interconnect_0_hex0_s1_write),                        //                                  .write
		.HEX0_s1_readdata                        (mm_interconnect_0_hex0_s1_readdata),                     //                                  .readdata
		.HEX0_s1_writedata                       (mm_interconnect_0_hex0_s1_writedata),                    //                                  .writedata
		.HEX0_s1_chipselect                      (mm_interconnect_0_hex0_s1_chipselect),                   //                                  .chipselect
		.HEX1_s1_address                         (mm_interconnect_0_hex1_s1_address),                      //                           HEX1_s1.address
		.HEX1_s1_write                           (mm_interconnect_0_hex1_s1_write),                        //                                  .write
		.HEX1_s1_readdata                        (mm_interconnect_0_hex1_s1_readdata),                     //                                  .readdata
		.HEX1_s1_writedata                       (mm_interconnect_0_hex1_s1_writedata),                    //                                  .writedata
		.HEX1_s1_chipselect                      (mm_interconnect_0_hex1_s1_chipselect),                   //                                  .chipselect
		.HEX2_s1_address                         (mm_interconnect_0_hex2_s1_address),                      //                           HEX2_s1.address
		.HEX2_s1_write                           (mm_interconnect_0_hex2_s1_write),                        //                                  .write
		.HEX2_s1_readdata                        (mm_interconnect_0_hex2_s1_readdata),                     //                                  .readdata
		.HEX2_s1_writedata                       (mm_interconnect_0_hex2_s1_writedata),                    //                                  .writedata
		.HEX2_s1_chipselect                      (mm_interconnect_0_hex2_s1_chipselect),                   //                                  .chipselect
		.HEX3_s1_address                         (mm_interconnect_0_hex3_s1_address),                      //                           HEX3_s1.address
		.HEX3_s1_write                           (mm_interconnect_0_hex3_s1_write),                        //                                  .write
		.HEX3_s1_readdata                        (mm_interconnect_0_hex3_s1_readdata),                     //                                  .readdata
		.HEX3_s1_writedata                       (mm_interconnect_0_hex3_s1_writedata),                    //                                  .writedata
		.HEX3_s1_chipselect                      (mm_interconnect_0_hex3_s1_chipselect),                   //                                  .chipselect
		.HEX4_s1_address                         (mm_interconnect_0_hex4_s1_address),                      //                           HEX4_s1.address
		.HEX4_s1_write                           (mm_interconnect_0_hex4_s1_write),                        //                                  .write
		.HEX4_s1_readdata                        (mm_interconnect_0_hex4_s1_readdata),                     //                                  .readdata
		.HEX4_s1_writedata                       (mm_interconnect_0_hex4_s1_writedata),                    //                                  .writedata
		.HEX4_s1_chipselect                      (mm_interconnect_0_hex4_s1_chipselect),                   //                                  .chipselect
		.HEX5_s1_address                         (mm_interconnect_0_hex5_s1_address),                      //                           HEX5_s1.address
		.HEX5_s1_write                           (mm_interconnect_0_hex5_s1_write),                        //                                  .write
		.HEX5_s1_readdata                        (mm_interconnect_0_hex5_s1_readdata),                     //                                  .readdata
		.HEX5_s1_writedata                       (mm_interconnect_0_hex5_s1_writedata),                    //                                  .writedata
		.HEX5_s1_chipselect                      (mm_interconnect_0_hex5_s1_chipselect),                   //                                  .chipselect
		.LEDS_s1_address                         (mm_interconnect_0_leds_s1_address),                      //                           LEDS_s1.address
		.LEDS_s1_write                           (mm_interconnect_0_leds_s1_write),                        //                                  .write
		.LEDS_s1_readdata                        (mm_interconnect_0_leds_s1_readdata),                     //                                  .readdata
		.LEDS_s1_writedata                       (mm_interconnect_0_leds_s1_writedata),                    //                                  .writedata
		.LEDS_s1_chipselect                      (mm_interconnect_0_leds_s1_chipselect),                   //                                  .chipselect
		.NIOSV_dm_agent_address                  (mm_interconnect_0_niosv_dm_agent_address),               //                    NIOSV_dm_agent.address
		.NIOSV_dm_agent_write                    (mm_interconnect_0_niosv_dm_agent_write),                 //                                  .write
		.NIOSV_dm_agent_read                     (mm_interconnect_0_niosv_dm_agent_read),                  //                                  .read
		.NIOSV_dm_agent_readdata                 (mm_interconnect_0_niosv_dm_agent_readdata),              //                                  .readdata
		.NIOSV_dm_agent_writedata                (mm_interconnect_0_niosv_dm_agent_writedata),             //                                  .writedata
		.NIOSV_dm_agent_readdatavalid            (mm_interconnect_0_niosv_dm_agent_readdatavalid),         //                                  .readdatavalid
		.NIOSV_dm_agent_waitrequest              (mm_interconnect_0_niosv_dm_agent_waitrequest),           //                                  .waitrequest
		.NIOSV_timer_sw_agent_address            (mm_interconnect_0_niosv_timer_sw_agent_address),         //              NIOSV_timer_sw_agent.address
		.NIOSV_timer_sw_agent_write              (mm_interconnect_0_niosv_timer_sw_agent_write),           //                                  .write
		.NIOSV_timer_sw_agent_read               (mm_interconnect_0_niosv_timer_sw_agent_read),            //                                  .read
		.NIOSV_timer_sw_agent_readdata           (mm_interconnect_0_niosv_timer_sw_agent_readdata),        //                                  .readdata
		.NIOSV_timer_sw_agent_writedata          (mm_interconnect_0_niosv_timer_sw_agent_writedata),       //                                  .writedata
		.NIOSV_timer_sw_agent_byteenable         (mm_interconnect_0_niosv_timer_sw_agent_byteenable),      //                                  .byteenable
		.NIOSV_timer_sw_agent_readdatavalid      (mm_interconnect_0_niosv_timer_sw_agent_readdatavalid),   //                                  .readdatavalid
		.NIOSV_timer_sw_agent_waitrequest        (mm_interconnect_0_niosv_timer_sw_agent_waitrequest),     //                                  .waitrequest
		.SDRAM_s1_address                        (mm_interconnect_0_sdram_s1_address),                     //                          SDRAM_s1.address
		.SDRAM_s1_write                          (mm_interconnect_0_sdram_s1_write),                       //                                  .write
		.SDRAM_s1_read                           (mm_interconnect_0_sdram_s1_read),                        //                                  .read
		.SDRAM_s1_readdata                       (mm_interconnect_0_sdram_s1_readdata),                    //                                  .readdata
		.SDRAM_s1_writedata                      (mm_interconnect_0_sdram_s1_writedata),                   //                                  .writedata
		.SDRAM_s1_byteenable                     (mm_interconnect_0_sdram_s1_byteenable),                  //                                  .byteenable
		.SDRAM_s1_readdatavalid                  (mm_interconnect_0_sdram_s1_readdatavalid),               //                                  .readdatavalid
		.SDRAM_s1_waitrequest                    (mm_interconnect_0_sdram_s1_waitrequest),                 //                                  .waitrequest
		.SDRAM_s1_chipselect                     (mm_interconnect_0_sdram_s1_chipselect),                  //                                  .chipselect
		.SWITCHES_s1_address                     (mm_interconnect_0_switches_s1_address),                  //                       SWITCHES_s1.address
		.SWITCHES_s1_readdata                    (mm_interconnect_0_switches_s1_readdata)                  //                                  .readdata
	);

	encrypt_irq_mapper irq_mapper (
		.clk           (clock_sys_clk_clk),              //       clk.clk
		.reset         (rst_controller_reset_out_reset), // clk_reset.reset
		.receiver0_irq (irq_mapper_receiver0_irq),       // receiver0.irq
		.sender_irq    (niosv_platform_irq_rx_irq)       //    sender.irq
	);

	altera_reset_controller #(
		.NUM_RESET_INPUTS          (1),
		.OUTPUT_RESET_SYNC_EDGES   ("deassert"),
		.SYNC_DEPTH                (2),
		.RESET_REQUEST_PRESENT     (0),
		.RESET_REQ_WAIT_TIME       (1),
		.MIN_RST_ASSERTION_TIME    (3),
		.RESET_REQ_EARLY_DSRT_TIME (1),
		.USE_RESET_REQUEST_IN0     (0),
		.USE_RESET_REQUEST_IN1     (0),
		.USE_RESET_REQUEST_IN2     (0),
		.USE_RESET_REQUEST_IN3     (0),
		.USE_RESET_REQUEST_IN4     (0),
		.USE_RESET_REQUEST_IN5     (0),
		.USE_RESET_REQUEST_IN6     (0),
		.USE_RESET_REQUEST_IN7     (0),
		.USE_RESET_REQUEST_IN8     (0),
		.USE_RESET_REQUEST_IN9     (0),
		.USE_RESET_REQUEST_IN10    (0),
		.USE_RESET_REQUEST_IN11    (0),
		.USE_RESET_REQUEST_IN12    (0),
		.USE_RESET_REQUEST_IN13    (0),
		.USE_RESET_REQUEST_IN14    (0),
		.USE_RESET_REQUEST_IN15    (0),
		.ADAPT_RESET_REQUEST       (0)
	) rst_controller (
		.reset_in0      (niosv_dbg_reset_out_reset),      // reset_in0.reset
		.clk            (clock_sys_clk_clk),              //       clk.clk
		.reset_out      (rst_controller_reset_out_reset), // reset_out.reset
		.reset_req      (),                               // (terminated)
		.reset_req_in0  (1'b0),                           // (terminated)
		.reset_in1      (1'b0),                           // (terminated)
		.reset_req_in1  (1'b0),                           // (terminated)
		.reset_in2      (1'b0),                           // (terminated)
		.reset_req_in2  (1'b0),                           // (terminated)
		.reset_in3      (1'b0),                           // (terminated)
		.reset_req_in3  (1'b0),                           // (terminated)
		.reset_in4      (1'b0),                           // (terminated)
		.reset_req_in4  (1'b0),                           // (terminated)
		.reset_in5      (1'b0),                           // (terminated)
		.reset_req_in5  (1'b0),                           // (terminated)
		.reset_in6      (1'b0),                           // (terminated)
		.reset_req_in6  (1'b0),                           // (terminated)
		.reset_in7      (1'b0),                           // (terminated)
		.reset_req_in7  (1'b0),                           // (terminated)
		.reset_in8      (1'b0),                           // (terminated)
		.reset_req_in8  (1'b0),                           // (terminated)
		.reset_in9      (1'b0),                           // (terminated)
		.reset_req_in9  (1'b0),                           // (terminated)
		.reset_in10     (1'b0),                           // (terminated)
		.reset_req_in10 (1'b0),                           // (terminated)
		.reset_in11     (1'b0),                           // (terminated)
		.reset_req_in11 (1'b0),                           // (terminated)
		.reset_in12     (1'b0),                           // (terminated)
		.reset_req_in12 (1'b0),                           // (terminated)
		.reset_in13     (1'b0),                           // (terminated)
		.reset_req_in13 (1'b0),                           // (terminated)
		.reset_in14     (1'b0),                           // (terminated)
		.reset_req_in14 (1'b0),                           // (terminated)
		.reset_in15     (1'b0),                           // (terminated)
		.reset_req_in15 (1'b0)                            // (terminated)
	);

endmodule
